AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sosw-orchestrator

  Sample sosw Orchestrator deployment with SAM.


Resources:

  SoswOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sosw_orchestrator/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 256
      Timeout: 60


Outputs:
  SoswOrchestratorFunction:
    Description: "sosw Orchestrator Essential Function"
    Value: !GetAtt SoswOrchestratorFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role for Orchestrator Essential Function"
    Value: !GetAtt SoswOrchestratorFunctionRole.Arn
